# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d52ae7019171ca668a1127765fcc53550fb2df99dbad1b3147e0d0b37c538fb6d1ac077d8d309043f792662d8cac7a0da0cf35302a58d3f16181c9762ad82741

test:
  secret_key_base: d3372ea2a8e16017beae18d9f49b736eb310c4b3dbbbec91b9d3eb22fe515eb16fa5b126498d7fb3488be1dff8d64bb641d4aff46af4c5305cb549da7f39097c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
